export enum CommonEnum {
  HEADER = 'Basic user information and Address',
  SUBMIT_USER_FORM = 'Submit User Form',
  ADD_ADDRESS = 'Add Address',
  REGISTER_USER_INFORMATION = 'Register User Information',
  SEARCH_ADDRESS = 'Search Address :',
  REVIEW_DETAILS = 'Review Details',
  REGISTER_USER_ADRESS = 'Register User Address',
  EMAIL_ADDRESS = 'Email Address',
  NAME = 'Name',
  PASSWORD = 'Password',
  ADDRESS_1 = 'Address Line 1',
  ADDRESS_2 = 'Address Line 2',
  CITY = 'City',
  STATE = 'State',
  COUNTRY = 'Country',
  POSTAL_CODE = 'Postal Code',
  UPLOAD_IMAGE = 'Upload IMAGE',
}
